name: PlatformIO CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install PlatformIO CLI
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build project
      run: |
        platformio run
        cd $GITHUB_WORKSPACE
        cp -f .pio/build/T-Beam-Stratux/firmware.bin bin/T-Beam-Stratux/v7.0.0/firmware.bin
        cp -f .pio/build/T-Beam-Stratux/partitions.bin bin/T-Beam-Stratux/v7.0.0/partitions.bin
        cp -f T-Beam-Stratux.csv bin/T-Beam-Stratux/v7.0.0/
        cp -f bin/bootloader_dio_40m.bin bin/T-Beam-Stratux/v7.0.0/bootloader.bin
        cp -f bin/boot_app0.bin bin/T-Beam-Stratux/v7.0.0/
        cp -f bin/psRam/v7.0.0/spiffs.bin bin/T-Beam-Stratux/v7.0.0/

    - uses: actions/upload-artifact@v4
      with:
        name: GXAirCom
        path: |
         bin/T-Beam-Stratux/
        if-no-files-found: error
