name: PlatformIO CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install PlatformIO CLI
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Build project
      run: |
        platformio run -e psRam
        platformio run -e T-Beam-S3Core

    - uses: actions/upload-artifact@v4
      with:
        name: GXAirCom
        path: |
         bin/psRam/v8.0.0/
         bin/T-Beam-S3Core/v8.0.0/
        if-no-files-found: error
