name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/gereic/GXAirCom.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Check for new commits
        id: check
        run: |
          COMMITS=$(git log HEAD..upstream/master --oneline || true)
          if [ -z "$COMMITS" ]; then
            echo "no new commits"
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "new commits found"
            echo "updated=true" >> $GITHUB_OUTPUT
          fi

      - name: Sync if needed
        if: steps.check.outputs.updated == 'true'
        run: |
          git fetch upstream
          git checkout master
          git merge upstream/master --allow-unrelated-histories
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VirusPilot/GXAirCom.git master
