name: Sync Fork

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream
        run: git remote add upstream https://github.com/gereic/GXAirCom.git

      - name: Fetch and merge upstream
        run: |
          git fetch upstream
          git checkout master
          git merge upstream/master --allow-unrelated-histories
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VirusPilot/GXAirCom.git master
